# Generated by Django 5.1.6 on 2025-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_barangayfilereport_barangaydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayFileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=255)),
                ('barangay_street', models.CharField(max_length=255)),
                ('severity_level', models.CharField(choices=[('Informational', 'Informational'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=20)),
                ('incident_year', models.IntegerField()),
                ('incident_month', models.CharField(max_length=20)),
                ('incident_day', models.IntegerField()),
                ('incident_time', models.TimeField()),
                ('incident_type', models.TextField(blank=True, null=True)),
                ('incident_description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='incident_attachments/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
