# Generated by Django 5.1.6 on 2025-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_barangayfilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayfilereport',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=11),
        ),
    ]
