# Generated by Django 5.1.6 on 2025-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_barangaydetails_user_barangayfilereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayfilereport',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangayfilereport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
